### ISSUE TITLE
Calyxコンテナ内でテストを並行実行できない

### ISSUE THREAD

**Issue by pddg** [StudioAquatan/Saffron#117]
```bash
#!/bin/bash -eo pipefail
cd calyx/src
pipenv run python manage.py migrate
pipenv run python manage.py test -v 2 --parallel
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, courses, sessions, users
Running migrations:
  Applying courses.0001_initial... OK
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying users.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying authtoken.0001_initial... OK
  Applying authtoken.0002_auto_20160226_1747... OK
  Applying courses.0002_course_users... OK
  Applying courses.0003_auto_20190101_2208... OK
  Applying courses.0004_course_admin_user_group... OK
  Applying courses.0005_config... OK
  Applying courses.0006_auto_20190106_1927... OK
  Applying courses.0007_auto_20190106_2333... OK
  Applying courses.0008_auto_20190112_0041... OK
  Applying sessions.0001_initial... OK
  Applying users.0002_auto_20181011_1355... OK
  Applying users.0003_user_joined... OK
  Applying users.0004_auto_20181228_1547... OK
  Applying users.0005_remove_user_course... OK
  Applying users.0006_auto_20190105_1656... OK
  Applying users.0007_remove_user_is_admin... OK
  Applying users.0008_auto_20190115_0006... OK
Creating test database for alias 'default' ('test_saffron')...
Operations to perform:
  Synchronize unmigrated apps: corsheaders, djoser, messages, rest_framework, rest_framework_jwt, rest_framework_swagger, staticfiles
  Apply all migrations: admin, auth, authtoken, contenttypes, courses, sessions, users
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
Running migrations:
  Applying courses.0001_initial... OK
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying users.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying authtoken.0001_initial... OK
  Applying authtoken.0002_auto_20160226_1747... OK
  Applying courses.0002_course_users... OK
  Applying courses.0003_auto_20190101_2208... OK
  Applying courses.0004_course_admin_user_group... OK
  Applying courses.0005_config... OK
  Applying courses.0006_auto_20190106_1927... OK
  Applying courses.0007_auto_20190106_2333... OK
  Applying courses.0008_auto_20190112_0041... OK
  Applying sessions.0001_initial... OK
  Applying users.0002_auto_20181011_1355... OK
  Applying users.0003_user_joined... OK
  Applying users.0004_auto_20181228_1547... OK
  Applying users.0005_remove_user_course... OK
  Applying users.0006_auto_20190105_1656... OK
  Applying users.0007_remove_user_is_admin... OK
  Applying users.0008_auto_20190115_0006... OK
Cloning test database for alias 'default' ('test_saffron')...
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/circleci/.local/share/virtualenvs/src-WL9Rm7Ux/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/circleci/.local/share/virtualenvs/src-WL9Rm7Ux/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/circleci/.local/share/virtualenvs/src-WL9Rm7Ux/lib/python3.7/site-packages/django/core/management/commands/test.py", line 26, in run_from_argv
    super().run_from_argv(argv)
  File "/home/circleci/.local/share/virtualenvs/src-WL9Rm7Ux/lib/python3.7/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/circleci/.local/share/virtualenvs/src-WL9Rm7Ux/lib/python3.7/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/home/circleci/.local/share/virtualenvs/src-WL9Rm7Ux/lib/python3.7/site-packages/django/core/management/commands/test.py", line 56, in handle
    failures = test_runner.run_tests(test_labels)
  File "/home/circleci/.local/share/virtualenvs/src-WL9Rm7Ux/lib/python3.7/site-packages/django/test/runner.py", line 604, in run_tests
    old_config = self.setup_databases()
  File "/home/circleci/.local/share/virtualenvs/src-WL9Rm7Ux/lib/python3.7/site-packages/django/test/runner.py", line 551, in setup_databases
    self.parallel, **kwargs
  File "/home/circleci/.local/share/virtualenvs/src-WL9Rm7Ux/lib/python3.7/site-packages/django/test/utils.py", line 181, in setup_databases
    keepdb=keepdb,
  File "/home/circleci/.local/share/virtualenvs/src-WL9Rm7Ux/lib/python3.7/site-packages/django/db/backends/base/creation.py", line 214, in clone_test_db
    self._clone_test_db(suffix, verbosity, keepdb)
  File "/home/circleci/.local/share/virtualenvs/src-WL9Rm7Ux/lib/python3.7/site-packages/django/db/backends/mysql/creation.py", line 55, in _clone_test_db
    self._clone_db(source_database_name, target_database_name)
  File "/home/circleci/.local/share/virtualenvs/src-WL9Rm7Ux/lib/python3.7/site-packages/django/db/backends/mysql/creation.py", line 64, in _clone_db
    dump_proc = subprocess.Popen(dump_cmd, stdout=subprocess.PIPE)
  File "/usr/local/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'mysqldump': 'mysqldump'
```

どうも `--parallel` フラグを付けると一旦migrateした後， `mysqldump` でスキーマの定義をバックアップ，別のDB名でリストアしてテスト用のDBを複数作成するようだ．
コンテナ内には `mysqldump` コマンドは存在しないため，失敗するようだ．

**Comment by pddg** [comment]
Calyxコンテナではなく `circleci/python:3.7` だった． `mysqldump` をインストールするよりもテストを逐次実行した方がおそらく速いので，今回は `--parallel` を諦める．
